apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: cloudflare-api
  namespace: cloudflare-tunnel-controller
spec:
  hostAPI: https://eu.infisical.com
  resyncInterval: 60
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical-system
      secretsScope:
        projectId: "8e0e5966-40b4-4a1c-9880-fdb6786167a9"
        envSlug: prod
        secretsPath: "/infrastructure/cloudflare"
  managedSecretReference:
    secretName: cloudflare-api
    secretNamespace: cloudflare-tunnel-controller
