cloudflare:
  secretRef:
    name: cloudflare-api
    accountIDKey: cloudflare-account-id
    tunnelNameKey: cloudflare-tunnel-name
    apiTokenKey: api-token

ingressClass:
  name: cloudflare-tunnel

cloudflared:
  image:
    repository: docker.io/cloudflare/cloudflared
    tag: latest@sha256:072c067d25ccbe61d46e18f0d0723255f2bb5304f7317caa95b27031520ff92c
  protocol: http2
