cloudflare:
  secretRef:
    name: cloudflare-api
    accountIDKey: cloudflare-account-id
    tunnelNameKey: cloudflare-tunnel-name
    apiTokenKey: api-token

ingressClass:
  name: cloudflare-tunnel

cloudflared:
  image:
    repository: docker.io/cloudflare/cloudflared
    tag: latest
