apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: pg-role-sonarr
  namespace: database
spec:
  hostAPI: https://eu.infisical.com
  resyncInterval: 60
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical-system
      secretsScope:
        projectId: "bebbc4ce-ab00-4776-aaba-0f3c89a93d1c"
        envSlug: prod
        secretsPath: "/downloads/sonarr"
  managedSecretReference:
    secretName: pg-role-sonarr
    secretNamespace: database
    template:
      includeAllSecrets: true
      metadata:
        labels:
          cnpg.io/reload: "true"
