---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/argoproj.io/application_v1alpha1.json
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tdarr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: git@github.com:andrewzn69/infra.git
      targetRevision: HEAD
      ref: infra
    - repoURL: oci://ghcr.io/andrewzn69/app-template
      targetRevision: 1.2.0
      path: .
      helm:
        releaseName: tdarr
        valueFiles:
          - $infra/apps/downloads/tdarr/values.yaml
  destination:
    name: vizima
    namespace: downloads
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
