persistence:
  enabled: false

admin:
  existingSecret: grafana-env
  userKey: GF_SECURITY_ADMIN_USER
  passwordKey: GF_SECURITY_ADMIN_PASSWORD

env:
  GF_DATABASE_TYPE: postgres
  GF_DATABASE_HOST: postgres-rw.database.svc.cluster.local:5432
  GF_DATABASE_NAME: grafana
  GF_DATABASE_SSL_MODE: require

envValueFrom:
  GF_DATABASE_USER:
    secretKeyRef:
      name: grafana-env
      key: username
  GF_DATABASE_PASSWORD:
    secretKeyRef:
      name: grafana-env
      key: password

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: VictoriaMetrics
        type: prometheus
        uid: victoriametrics
        url: http://victoria-metrics-victoria-metrics-single-server.observability.svc.cluster.local:8428
        access: proxy
        isDefault: true
      - name: Loki
        type: loki
        uid: loki
        url: http://loki.observability.svc.cluster.local:3100
        access: proxy
      - name: VictoriaTraces
        type: jaeger
        uid: victoriatraces
        url: http://victoria-traces-vt-single-server.observability.svc.cluster.local:10428/select/jaeger
        access: proxy

route:
  main:
    enabled: true
    apiVersion: gateway.networking.k8s.io/v1
    kind: HTTPRoute
    hostnames:
      - grafana.internal.zemn.xyz
    parentRefs:
      - name: internal
        namespace: gateway-system
        sectionName: https

testFramework:
  enabled: false

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    memory: 1Gi

extraObjects:
  - apiVersion: secrets.infisical.com/v1alpha1
    kind: InfisicalSecret
    metadata:
      name: grafana-env
    spec:
      hostAPI: https://eu.infisical.com
      resyncInterval: 60
      authentication:
        universalAuth:
          credentialsRef:
            secretName: infisical-universal-auth
            secretNamespace: infisical-system
          secretsScope:
            projectId: "bebbc4ce-ab00-4776-aaba-0f3c89a93d1c"
            envSlug: prod
            secretsPath: "/observability/grafana"
      managedSecretReference:
        secretName: grafana-env
        secretNamespace: observability
