apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lidarr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: git@github.com:andrewzn69/infra.git
      targetRevision: HEAD
      ref: infra
    - repoURL: oci://ghcr.io/andrewzn69/app-template
      targetRevision: 1.1.0
      path: .
      helm:
        releaseName: lidarr
        valueFiles:
          - $infra/apps/downloads/lidarr/values.yaml
  destination:
    name: vizima
    namespace: downloads
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
