apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-connector-novigrad
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:andrewzn69/infra.git
    targetRevision: HEAD
    path: apps/infrastructure/tailscale/connector/novigrad
    directory:
      exclude: "application.yaml"
  destination:
    name: novigrad
    namespace: tailscale-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
