apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: tailscale-oauth
  namespace: tailscale-system
spec:
  hostAPI: https://eu.infisical.com
  resyncInterval: 60
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical-system
      secretsScope:
        projectId: "bebbc4ce-ab00-4776-aaba-0f3c89a93d1c" # change
        envSlug: prod
        secretsPath: "/infrastructure/tailscale"
  managedSecretReference:
    secretName: operator-oauth
    secretNamespace: tailscale-system
