apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metrics-server
  namespace: argocd
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: metrics-server-{{name}}
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      sources:
        - repoURL: git@github.com:andrewzn69/infra.git
          targetRevision: HEAD
          ref: infra
        - repoURL: https://kubernetes-sigs.github.io/metrics-server/
          chart: metrics-server
          targetRevision: 3.13.1
          helm:
            releaseName: metrics-server
            valueFiles:
              - $infra/apps/infrastructure/metrics-server/values.yaml
      destination:
        server: "{{server}}"
        namespace: kube-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
