apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: git@github.com:andrewzn69/infra.git
      targetRevision: HEAD
      ref: infra
    - repoURL: https://grafana-community.github.io/helm-charts
      chart: loki
      targetRevision: 18.11.2
      helm:
        releaseName: loki
        valueFiles:
          - $infra/apps/observability/loki/values.yaml
  destination:
    name: vizima
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
