apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: git@github.com:andrewzn69/infra.git
      targetRevision: HEAD
      ref: infra
    - repoURL: https://victoriametrics.github.io/helm-charts
      chart: victoria-metrics-single
      targetRevision: 0.45.0
      helm:
        releaseName: victoria-metrics
        valueFiles:
          - $infra/apps/observability/victoria-metrics/values.yaml
  destination:
    name: vizima
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
