namespace: downloads

secrets:
  enabled: true
  type: infisical
  infisical:
    hostAPI: https://eu.infisical.com
    projectSlug: vizima
    envSlug: prod
    secretsPath: "/downloads/sonarr"
    auth:
      credentialsSecretName: infisical-universal-auth
      credentialsSecretNamespace: infisical-system
    managedSecret:
      creationPolicy: Owner

components:
  sonarr:
    image:
      repository: ghcr.io/home-operations/sonarr
      tag: "4.0.17"
      pullPolicy: IfNotPresent

    service:
      type: ClusterIP
      port: 8989
      targetPort: 8989
      protocol: TCP
      name: http

    gateway:
      enabled: true
      gatewayName: internal
      gatewayNamespace: gateway-system
      hostname: sonarr.internal.zemn.xyz
      paths:
        - path: /
          pathType: PathPrefix

    volumes:
      pvc:
        - name: config
          mountPath: /config
          size: 5Gi
          readOnly: false
          accessMode: ReadWriteOnce
          storageClassName: longhorn

      nfs:
        - name: shows
          mountPath: /tv
          server: "100.64.100.10"
          path: "/storage/media/shows"
          readOnly: false
        - name: downloads
          mountPath: /downloads
          server: "100.64.100.10"
          path: "/storage/downloads"
          readOnly: false

      emptyDir:
        - name: tmp
          mountPath: /tmp

    resources:
      requests:
        memory: 192Mi
        cpu: 50m
      limits:
        memory: 384Mi
        cpu: 500m

    env:
      - name: TZ
        value: "Europe/Prague"
      - name: SONARR__POSTGRES__HOST
        value: "postgres-rw.database.svc.cluster.local"
      - name: SONARR__POSTGRES__PORT
        value: "5432"
      - name: SONARR__POSTGRES__MAINDB
        value: "sonarr"
      - name: SONARR__POSTGRES__USER
        valueFrom:
          secretKeyRef:
            name: sonarr
            key: username
      - name: SONARR__POSTGRES__PASSWORD
        valueFrom:
          secretKeyRef:
            name: sonarr
            key: password
      - name: SONARR__LOG__DBENABLED
        value: "False"

    replicaCount: 0

    securityContext:
      runAsUser: 10001
      runAsGroup: 10001
      fsGroup: 10001
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL

    configMap:
      enabled: false

    initContainers:
      fixPermissions:
        enabled: false

    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false

    metrics:
      enabled: false
