apiVersion: v1
kind: Service
metadata:
  name: novigrad-oke-api
  namespace: tailscale-system
  annotations:
    tailscale.com/tailnet-ip: "10.0.0.155"
    tailscale.com/proxy-class: accept-routes
spec:
  type: ExternalName
  externalName: placeholder
  ports:
    - port: 6443
      protocol: TCP
      name: https
