namespace: downloads

secrets:
  enabled: true
  type: infisical
  infisical:
    hostAPI: https://eu.infisical.com
    projectSlug: vizima
    envSlug: prod
    secretsPath: "/downloads/recyclarr"
    auth:
      credentialsSecretName: infisical-universal-auth
      credentialsSecretNamespace: infisical-system
    managedSecret:
      creationPolicy: Owner

components:
  recyclarr:
    image:
      repository: ghcr.io/recyclarr/recyclarr
      tag: "8.6.0"
      pullPolicy: IfNotPresent

    service:
      enabled: false

    volumes:
      pvc:
        - name: config
          mountPath: /config
          size: 1Gi
          readOnly: false
          accessMode: ReadWriteOnce
          storageClassName: longhorn
      emptyDir:
        - name: tmp
          mountPath: /tmp

    resources:
      requests:
        memory: 36Mi
        cpu: 5m
      limits:
        memory: 128Mi

    env:
      - name: TZ
        value: "Europe/Prague"
      - name: CRON_SCHEDULE
        value: "@daily"
      - name: RECYCLARR_CREATE_CONFIG
        value: "false"
      - name: RADARR_API_KEY
        valueFrom:
          secretKeyRef:
            name: recyclarr
            key: radarr_api_key
      - name: SONARR_API_KEY
        valueFrom:
          secretKeyRef:
            name: recyclarr
            key: sonarr_api_key

    configMap:
      enabled: true
      mountPath: /config/recyclarr.yml
      subPath: recyclarr.yml
      files:
        recyclarr.yml: |
          # yaml-language-server: $schema=https://schemas.recyclarr.dev/v8/config-schema.json

          radarr:
            movies:
              base_url: http://radarr.downloads.svc.cluster.local:7878
              api_key: !env_var RADARR_API_KEY

              quality_definition:
                type: movie

              quality_profiles:
                - name: SQP-1 (1080p)
                  trash_id: 0896c29d74de619df168d23b98104b22
                  reset_unmatched_scores:
                    enabled: true
                  qualities:
                    - name: Bluray|WEB-1080p
                      qualities:
                        - Bluray-1080p
                        - WEBRip-1080p
                        - WEBDL-1080p

              media_naming:
                folder: jellyfin-tmdb
                movie:
                  rename: true
                  standard: jellyfin-tmdb

          sonarr:
            series:
              base_url: http://sonarr.downloads.svc.cluster.local:8989
              api_key: !env_var SONARR_API_KEY

              quality_definition:
                type: series

              quality_profiles:
                - trash_id: 72dae194fc92bf828f32cde7744e51a1  # web-1080p
                  reset_unmatched_scores:
                    enabled: true

              media_naming:
                series: jellyfin-tvdb
                season: default
                episodes:
                  rename: true
                  standard: default

    replicaCount: 0

    securityContext:
      runAsUser: 10001
      runAsGroup: 10001
      fsGroup: 10001
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL

    initContainers:
      fixPermissions:
        enabled: false

    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false

    metrics:
      enabled: false
