apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: internal-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:andrewzn69/infra.git
    targetRevision: HEAD
    path: apps/infrastructure/internal-gateway
  destination:
    name: vizima
    namespace: gateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
