apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:andrewzn69/infra.git
    targetRevision: HEAD
    path: apps/infrastructure
    directory:
      recurse: true
      include: "**/{application,applicationset}.yaml"
  destination:
    name: vizima
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
