apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-connector-vizima
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/andrewzn69/infra
    targetRevision: HEAD
    path: apps/infrastructure/tailscale/connector/vizima
  destination:
    name: vizima
    namespace: tailscale-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
