apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: database
spec:
  instances: 3
  storage:
    size: 30Gi
    storageClass: longhorn-cnpg
  resources:
    requests:
      cpu: 100m
      memory: 1Gi
    limits:
      memory: 1Gi
  managed:
    roles:
      - name: bazarr
        ensure: present
        login: true
        passwordSecret:
          name: pg-role-bazarr
      - name: invidious
        ensure: present
        login: true
        passwordSecret:
          name: pg-role-invidious
      - name: lidarr
        ensure: present
        login: true
        passwordSecret:
          name: pg-role-lidarr
      - name: materialious
        ensure: present
        login: true
        passwordSecret:
          name: pg-role-materialious
      - name: prowlarr
        ensure: present
        login: true
        passwordSecret:
          name: pg-role-prowlarr
      - name: radarr
        ensure: present
        login: true
        passwordSecret:
          name: pg-role-radarr
      - name: sonarr
        ensure: present
        login: true
        passwordSecret:
          name: pg-role-sonarr
      - name: grafana
        ensure: present
        login: true
        passwordSecret:
          name: pg-role-grafana
