apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: cert-manager-cloudflare-token
  namespace: cert-manager
spec:
  hostAPI: https://eu.infisical.com
  resyncInterval: 60
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical-system
      secretsScope:
        projectId: "bebbc4ce-ab00-4776-aaba-0f3c89a93d1c"
        envSlug: prod
        secretsPath: "/infrastructure/cert-manager"
  managedSecretReference:
    secretName: cert-manager-cloudflare-dns-token
    secretNamespace: cert-manager
